[settings]
lockfile = true
lockfile_platforms = ["macos-arm64", "linux-arm64"]

[env]
_.path = ["./scripts"]

[tools]
colima = { version = "latest", os = ["macos"] }
docker-cli = { version = "latest", os = ["macos"] }
lima = { version = "latest", os = ["macos"] }
