#!/usr/bin/env python3
"""Write the URLs worth offering a crawler, as sitemaps.org XML.

Revisions are deliberately absent. There are 1,532 of them, each page a list of
what a commit pinned, and they are the one corner of the site that reads as
bulk near-duplicate pages rather than as something a person searched for.

`limit` caps how many package URLs the sitemap offers. Every attribute is a
real page and could be listed — 31,878 fits inside the 50,000-URL limit — but
nothing here is prerendered, so whether one gets indexed depends on Google
choosing to run its JavaScript. Offering a slice first makes that measurable in
Search Console: if most of these land, raise the number; if almost none do, the
answer is prerendering, not more URLs. The slice is the attributes with the
most versions, as the closest thing to a popularity signal the index holds.

    sitemap.py <origin> <versions.json> <revisions.json> <releases.json> \
        <docs-dir> <dest.xml> <limit>
"""
import json
import os
import sys
from urllib.parse import quote
from xml.sax.saxutils import escape

(origin, versions_src, revisions_src, releases_src, docs_dir, dest, limit) = sys.argv[
    1:8
]
limit = int(limit)

versions = json.load(open(versions_src))["attrs"]
revisions = json.load(open(revisions_src))
releases = json.load(open(releases_src))

# The index is only as fresh as its newest revision, which is what every page
# not about one package or one release last changed on.
newest = revisions[-1]["date"]

urls = [("/", newest)]
for view in ("revisions", "releases", "stats"):
    urls.append((f"/?view={view}", newest))

# The documentation. Worth listing ahead of any package page: it is the only
# prerendered prose on the site — every other URL here is an empty shell that
# JavaScript fills in from JSON — so it is the one part a crawler can read
# without choosing to run anything.
#
# No lastmod, deliberately. Nothing in this build knows when a docs page last
# changed; `newest` is the wrong answer, because the docs do not move when the
# channel does, and a lastmod that lies every hour is worse than none at all.
#
# Offered without the `.html` the file on disk carries, matching the links the
# pages use and the URL a reader would type. Listing what is actually in the
# directory is what keeps this in step with whatever render-docs.py produced.
docs_files = sorted(f for f in os.listdir(docs_dir) if f.endswith(".html"))
urls.append(("/docs/", None))
for page in docs_files:
    if page != "index.html":
        urls.append((f"/docs/{page[:-5]}", None))

for name, r in releases.items():
    urls.append((f"/?view=releases&release={quote(name, safe='')}", r["date"]))

# A package's lastmod is the date of the newest revision shipping any of its
# versions: the last time the page's content changed. Truthful per-URL dates are
# what let a crawler skip the 20,000 packages that have not moved in years.
ranked = sorted(versions.items(), key=lambda kv: (-len(kv[1]), kv[0]))
for attr, vers in ranked[:limit]:
    # quote() with no safe characters, so the one attribute named with a "+"
    # survives: a bare + in a query string is a space.
    urls.append(
        (
            f"/?pkg={quote(attr, safe='')}",
            revisions[max(vers.values())]["date"],
        )
    )

with open(dest, "w") as out:
    out.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    out.write(
        "<!-- Generated by the site build. "
        f"{len(ranked[:limit])} of {len(ranked)} packages, "
        "the ones with the most versions. -->\n"
    )
    out.write('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n')
    for path, lastmod in urls:
        loc = escape(origin + path)
        mod = f"<lastmod>{lastmod}</lastmod>" if lastmod else ""
        out.write(f"<url><loc>{loc}</loc>{mod}</url>\n")
    out.write("</urlset>\n")

print(
    f"sitemap: {len(urls)} urls "
    f"({len(docs_files)} docs, {len(ranked) - limit} packages left out)"
)
