#!/usr/bin/env python3
"""Choose no-op, metadata-only publication, or incremental store-data work."""
import json
from pathlib import Path
import sys

# Bump deliberately when store-data generation changes require a refresh.
STORE_GENERATOR = 1


def plan(previous, work):
    previous, work = Path(previous), Path(work)
    read = lambda path: json.loads(path.read_text())
    old = read(previous / "revisions.json")
    new = read(work / "revisions.json")
    if new[: len(old)] != old:
        raise ValueError("Revision offsets changed; refusing an incremental merge")
    if new != old:
        return "update"
    stamp = previous / "state/store-generator.json"
    # Snapshots predating this gate were generated by version 1.
    if stamp.exists() and read(stamp)["version"] != STORE_GENERATOR:
        return "update"
    paths = list((previous / "artifacts").glob("outpaths-*.json"))
    if not paths:
        return "update"
    for path in paths:
        system = path.name.removeprefix("outpaths-")
        for name in (path.name, "tip-outpaths-" + system):
            file = previous / "artifacts" / name
            if not file.exists() or read(file)["revisionCount"] != len(new):
                return "update"
    if read(previous / "releases.json") != read(work / "releases.json"):
        return "metadata"
    return "none"


if __name__ == "__main__":
    print(plan(*sys.argv[1:]))
